simple-java-service:
  applicationName: customers
  version: "203c9ba"
  port: 8080
  targetPort: 8080
  deploymentStrategy:
    type: Rolling
    timeout: 300
    rollingUpdatePeriod: 1
    rollingInterval: 1
    rollingMaxSurge: 25%
    rollingMaxUnavailable: 20%
  replicaCount: 1
  health:
    livenessEndpoint: /health/live
    readinessEndpoint: /health/ready
    probeDelay: 5
    probePeriod: 10
    probeTimeout: 2
  imageURL: "image-registry.openshift-image-registry.svc:5000/order-management/customers"
  env: []
