simple-java-service:
  applicationName: orders
  version: "9d63b31"
  port: 8080
  targetPort: 8080
  deploymentStrategy:
    type: Rolling
    timeout: 300
    rollingUpdatePeriod: 1
    rollingInterval: 1
    rollingMaxSurge: 25%
    rollingMaxUnavailable: 20%
  replicaCount: 1
  health:
    livenessEndpoint: /actuator/health
    readinessEndpoint: /actuator/health
    probeDelay: 30
    probePeriod: 10
    probeTimeout: 2
  imageURL: "image-registry.openshift-image-registry.svc:5000/order-management/orders"
  env: []
