quarkus:
  kubernetes-client:
    trust-certs: true
  kubernetes-config:
    enabled: true
    config-maps:
      - inventory-config
  hibernate-orm:
    database:
      generation: drop-and-create
    sql-load-script: load.sql
  datasource:
    db-kind: postgresql   
    username: inventory
    password: inventory
    jdbc:
      url: jdbc:postgresql://localhost:5432/inventory
  
  log:
    level: INFO
    category:
      "org.meetup.openshift.rhoar":
        level: DEBUG
  jaeger:
    endpoint: http://jaeger-collector.rhoar.svc:14268/api/traces
    sampler-type: const
    sampler-param: 1

"%test":
  quarkus:
    datasource:    
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:inventory;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE